services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    env_file:
      - .env
    init: true
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - fabplay_data:/app/data

volumes:
  fabplay_data:
